---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-job
data:
  application.properties: |
    spring.application.name=sample-job
    
    spring.datasource.url=jdbc:mysql://127.0.0.1:3306/spring_batch?useSSL=false&useUnicode=true&characterEncoding=utf-8
    spring.datasource.username=root
    spring.datasource.password=password
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.hikari.maximum-pool-size=5
    spring.datasource.hikari.minimum-idle=2